USE [Ailanthus]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ADM_FACEPRINT](
	[FACEPRINT_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[EMPLOYEE_ID] [nvarchar](50) NOT NULL,
	[FACEPRINT] [varchar](max) NOT NULL,
	[CREATED_DATE] [datetime] NULL,
	[UPDATED_DATE] [datetime] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO